### PR TITLE
choices counts issue in filter panel

### LINKED ISSUE #579: [Bug]: The choices are not sorted for factor and ordered data types
### What happened?

The factor and ordered choices are not sorted anymore. They used to be sorted before.

Screenshot 2024-04-23 at 12 33 08 PM

<details>
  <summary>Sample app to reproduce the error</summary>
  
  ```r
library(teal)
library(shiny)
library(scda)
devtools::load_all("teal.slice")

ADSL <- synthetic_cdisc_data("latest")$adsl
ADSL$empty <- NA
ADSL$logical1 <- FALSE
ADSL$logical <- sample(c(TRUE, FALSE), size = nrow(ADSL), replace = TRUE)
ADSL$numeric <- rnorm(nrow(ADSL))
ADSL$numeric_categorical <- sample(1:3, size = nrow(ADSL), replace = TRUE)
ADSL$categorical <- sample(letters[1:10], size = nrow(ADSL), replace = TRUE)
ADSL$ordered <- ordered(sample(letters[1:10], size = nrow(ADSL), replace = TRUE))
ADSL$date <- Sys.Date() + seq_len(nrow(ADSL))
ADSL$datetime <- Sys.time() + seq_len(nrow(ADSL)) * 3600 * 12
ADSL$factor <- factor(sample(letters[1:4], size = nrow(ADSL), replace = TRUE))

ADSL$numeric[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$numeric[sample(1:nrow(ADSL), size = 10, )] <- Inf
ADSL$numeric[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$logical[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$date[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$datetime[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$categorical[sample(1:nrow(ADSL), size = 10, )] <- NA

ADTTE <- synthetic_cdisc_data("latest")$adtte
ADRS <- synthetic_cdisc_data("latest")$adrs


app <- init(
  data = teal_data(ADSL = ADSL, ADTTE = ADTTE, ADRS = ADRS),
  modules = list(example_module()),
  filter = teal_slices(
    teal_slice("ADSL", "empty"),
    teal_slice("ADSL", "logical1"),
    teal_slice("ADSL", "logical"),
    teal_slice("ADSL", "numeric"),
    teal_slice("ADSL", "numeric_categorical"),
    teal_slice("ADSL", "categorical"),
    teal_slice("ADSL", "ordered"),
    teal_slice("ADSL", "factor"),
    teal_slice("ADSL", "date"),
    teal_slice("ADSL", "datetime")
  )
)

runApp(app)
```
</details>

```r
pkgload::load_all()

# Factor
data <- data.frame(var = factor(c("small", "medium", "large")))
fstate <- teal.slice:::init_filter_state(
  x = data$var,
  slice = teal_slice(
    dataname = "x",
    varname = "var",
    selected = c("small", "medium"),
  )
)
fstate$.__enclos_env__$private$get_choices()

# Ordered
data <- data.frame(var = ordered(c("small", "medium", "large")))
fstate <- teal.slice:::init_filter_state(
  x = data$var,
  slice = teal_slice(
    dataname = "x",
    varname = "var",
    selected = c("small", "medium"),
  )
)
fstate$.__enclos_env__$private$get_choices()
```
Expectation is that we will get the choices in a sorted order: `"large", "medium", "small"`
But, we get: `"small", "medium", "large"` which is the order observed in the raw data.

### sessionInfo()

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by gogonzo**
Closes #579

Fix a bug after #576 - in previous PR I've changed accidentaly order of `choices` to be dependent on a data and not on the factor levels. Which led to the situation in the exploratory app that SEX choices was M, F while its counts was F, M. You can test it by:

- run exploratory app as is, look at the filter-panel you'll see the red error there
image

- comment out `count_type = "all"` in the exploratory code and run again. No red errors but the filtered counts doesn't match its filters

image

This PR fixes the problem as both counts and choices are set by the same value.

### CODE REVIEW

**Review by m7pr — APPROVED** [review]

**Comment by m7pr** [comment]
@gogonzo two tests are failing

**Comment by gogonzo** [comment]
Limited choices caused failure on counts - reproducible also in the release version. This PR fixes this

```r
library(teal)
library(shiny)
library(scda)

ADSL <- synthetic_cdisc_data("latest")$adsl
ADSL$empty <- NA
ADSL$logical1 <- FALSE
ADSL$logical <- sample(c(TRUE, FALSE), size = nrow(ADSL), replace = TRUE)
ADSL$numeric <- rnorm(nrow(ADSL))
ADSL$numeric_categorical <- sample(1:3, size = nrow(ADSL), replace = TRUE)
ADSL$categorical <- sample(letters[1:10], size = nrow(ADSL), replace = TRUE)
ADSL$ordered <- ordered(sample(letters[1:10], size = nrow(ADSL), replace = TRUE))
ADSL$date <- Sys.Date() + seq_len(nrow(ADSL))
ADSL$datetime <- Sys.time() + seq_len(nrow(ADSL)) * 3600 * 12

ADSL$numeric[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$numeric[sample(1:nrow(ADSL), size = 10, )] <- Inf
ADSL$numeric[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$logical[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$date[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$datetime[sample(1:nrow(ADSL), size = 10, )] <- NA
ADSL$categorical[sample(1:nrow(ADSL), size = 10, )] <- NA

ADTTE <- synthetic_cdisc_data("latest")$adtte
ADRS <- synthetic_cdisc_data("latest")$adrs

pkgload::load_all("teal.slice")
app <- init(
  data = teal_data(ADSL = ADSL, ADTTE = ADTTE, ADRS = ADRS),
  modules = list(example_module()),
  filter = teal_slices(
    teal_slice("ADSL", "empty"),
    teal_slice("ADSL", "numeric_categorical", choices = unique(ADSL$numeric_categorical)[1:2]),
    teal_slice("ADSL", "categorical", choices = unique(ADSL$categorical)[1:2]),
    teal_slice("ADSL", "ordered", choices = unique(ADSL$ordered)[1:2]),
    teal_slice("ADSL", "date", choices = unique(ADSL$data)[1:2]),
    teal_slice("ADSL", "datetime", choices = unique(ADSL$datetime)[1:2]),
    count_type = "all"
  )
)

runApp(app)

```

image

File: R/FilterStateChoices.R [hunk 1]
```diff
@@ -242,8 +240,10 @@ ChoicesFilterState <- R6::R6Class( # nolint
     # Checks validity of the choices, adjust if neccessary and sets the flag for the case where choices
     #  are limited by default from the start.
     set_choices = function(choices) {
+      ordered_counts <- table(as.character(private$x))
```
Comment (gogonzo) [inline R/FilterStateChoices.R:243]: @vedhav I'll make one change to not loose factor orders
